version: "3"

services:
  ####################
  # PHP server
  ####################
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    ports:
      - ${NODE_PORT:-5173}:5173
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html
    networks:
      - backend

  ####################
  # Web server
  ####################
  web:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT:-8080}:80
    depends_on:
      - app
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend

  ####################
  # DB server
  ####################
  db:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-test_db}
      - MYSQL_USER=${DB_USERNAME:-testuser}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
    networks:
      - backend

  ####################
  # phpMyAdmin
  ####################
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PMA_PORT:-8888}:80"
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    restart: always
    networks:
      - backend

  ####################
  # Mailpit
  ####################
  mailpit:
    image: "axllent/mailpit:latest"
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - backend

volumes:
  db-store:

networks:
  backend:
    driver: bridge
